# Generated by Django 4.1.6 on 2023-04-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdata", "0002_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_activate",
            field=models.BooleanField(default=False),
        ),
    ]
