name: Social Network MaksiX

on:
    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: windows-2022
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              uses : actions/setup-python@v3
              with:
                python-version: '3.11'
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Migrations
              run: |
                python manage.py makemigrations
                python manage.py migrate

            - name: Test with pytest
              run: |
                python manage.py test

            - name: Run linter ruff
              run: |
                ruff .