# Generated by Django 4.1.6 on 2023-02-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_alter_userprofile_address_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'Женский')], max_length=7),
        ),
    ]
