name: Social Network MaksiX

on:
    push:
        branches:
            - develop
    pull_request:
        base:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres:15.1-alpine
            env:
              POSTGRES_DB: ${{ vars.DBB_NAME }}
              POSTGRES_USER: ${{secrets.DB_USER }}
              POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD }}
            ports: [ '5432:5432' ]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses : actions/setup-python@v3
              with:
                python-version: '3.10.5'

            - name: Install dependencies
              run: |    
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Migrations
              run: |
                cd "Social Network MaksiX"
                python manage.py migrate
              env:
                SECRET_KEY: ${{ secrets.SECRET_KEY }}
                DB_NAME: ${{ vars.DBB_NAME }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_PORT: ${{ secrets.DB_PORT }}
                EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
                EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
                DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}

            - name: Test with pytest
              run: |
                cd "Social Network MaksiX"
                python manage.py test
              env:
                SECRET_KEY: ${{ secrets.SECRET_KEY }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_PORT: ${{ secrets.DB_PORT }}
                EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
                EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
                DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}

            - name: Run linter ruff
              run: |
                cd "Social Network MaksiX"
                ruff .
