name: Social Network MaksiX

on:
    push:
        branches:
            - develop
    pull_request:
        base:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses : actions/setup-python@v3
              with:
                python-version: '3.10.5'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Search directory
              run: |
                pwd
                cd ..
                cd "Social Network MaksiX"
                pwd

            - name: Test with pytest
              run: |
                pwd
                cd ..
                cd "Social Network MaksiX"
                pwd
                python manage.py test

            - name: Run linter ruff
              run: |
                cd ..
                cd "Social Network MaksiX"
                ruff .
