name: Social_Network_MaksiX

on:
    push:
        branches:
            - develop
    pull_request:
        base:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres:15.1-alpine
            env:
              POSTGRES_DB: ${{ vars.DB_NAME }}
              POSTGRES_USER: ${{vars.DB_USER }}
              POSTGRES_PASSWORD: ${{vars.DB_PASSWORD }}
            ports: [ '5432:5432' ]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses : actions/setup-python@v3
              with:
                python-version: '3.10.5'

            - name: Install dependencies
              run: |    
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Migrations
              run: |
                cd "Social_Network_MaksiX"
                python manage.py migrate
              env:
                SECRET_KEY: ${{ vars.SECRET_KEY }}
                DB_NAME: ${{ vars.DB_NAME }}
                DB_USER: ${{ vars.DB_USER }}
                DB_PASSWORD: ${{ vars.DB_PASSWORD }}
                DB_HOST: ${{ vars.DB_HOST }}
                DB_PORT: ${{ vars.DB_PORT }}
                EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
                EMAIL_HOST_PASSWORD: ${{ vars.EMAIL_HOST_PASSWORD }}
                DEFAULT_FROM_EMAIL: ${{ vars.DEFAULT_FROM_EMAIL }}

            - name: Test with pytest
              run: |
                cd "Social_Network_MaksiX"
                python manage.py test
              env:
                SECRET_KEY: ${{ vars.SECRET_KEY }}
                DB_NAME: ${{ vars.DB_NAME }}
                DB_USER: ${{ vars.DB_USER }}
                DB_PASSWORD: ${{ vars.DB_PASSWORD }}
                DB_HOST: ${{ vars.DB_HOST }}
                DB_PORT: ${{ vars.DB_PORT }}
                EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
                EMAIL_HOST_PASSWORD: ${{ vars.EMAIL_HOST_PASSWORD }}
                DEFAULT_FROM_EMAIL: ${{ vars.DEFAULT_FROM_EMAIL }}

            - name: Run linter ruff
              run: |
                cd "Social_Network_MaksiX"
                ruff .
